---
title: "git_00"
author: "Daniel"
date: "Year 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
A Mother's breast:

Safe refuge from her childish fears,

From childish troubles, childish tears,

Mists that enshroud her dawning years!

see how in sleep she seems to sing

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,

And sorry I could not travel both

And be one traveler, long I stood

And looked down one as far as I could

To where it bent in the undergrowth;

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,
    
 Shining with all his might:

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Traveler, your footprints

are the only road, nothing else.

Traveler, there is no road;

you make your own path as you walk.

As you walk, you make your own road,

and when you look back

you see the path

you will never travel again.

Traveler, there is no road;

only a ship's wake on the sea.